# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the Mord statistic
#'
#' @param item_no The item number
#' @param LCprob Item parameters
#' @param prior Class membership probabilities
#' @author Wenchao Ma, https://github.com/Wenchao-Ma/GDINA
#' @export
#'
#' @example
#'  pi_matrix <- matrix(c(.3, .8, .2, .7, .15, .77, .24, .90, .30, .65),
#'                      nrow = 5, ncol = 2, byrow = TRUE)
#'  base_rates <- c(.5, .5)
#'  partitioned_cov_mat <- Mord(c(1:5), pi_matrix, base_rates)
#'  Mord(c(1:5), pi_matrix, base_rates)
Mord <- function(item_no, LCprob, prior) {
    .Call(`_dcm2_Mord`, item_no, LCprob, prior)
}

